#!/bin/sh

setxkbmap us -variant altgr-intl

mon_qty=$(mons | grep Monitors | cut -d ":" -f 2)

if [ $mon_qty == "2" ]; then
    mons -s
    # TODO: don't hardcode
    xrandr --output HDMI1 --mode 3440x1440
fi

xcompmgr &
xwallpaper --maximize $XWALLPAPER
exec dwm
