source ~/.bash_profile

# ensure compatibility tmux <-> direnv
# https://github.com/direnv/direnv/issues/106#issuecomment-1027330218
if [ -n "$TMUX" ] && [ -n "$DIRENV_DIR" ]; then
    unset "${!DIRENV_@}"  # unset env vars starting with DIRENV_
fi
eval "$(direnv hook bash)"
